# Generated by Django 4.2.7 on 2023-12-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='blank_thumbnail.png', upload_to='thumbnails'),
        ),
    ]
