# Generated by Django 4.2.7 on 2023-12-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='church_banner',
            field=models.ImageField(default='blank_banner.png', upload_to='church_banners'),
        ),
        migrations.AddField(
            model_name='profile',
            name='founded_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='introductory_video_file',
            field=models.FileField(blank=True, upload_to='introductory-videos'),
        ),
    ]
